# Generated by Django 4.2.5 on 2023-09-12 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_alter_recipe_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('prep_time', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='CocktailIngredient',
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.cocktail'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.cocktail'),
        ),
        migrations.AlterField(
            model_name='review',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.cocktail'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
