# Generated by Django 4.2.5 on 2023-09-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_cocktail_rename_recipeingredient_cocktailingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='recipe_id',
            new_name='cocktail_id',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe_id',
            new_name='cocktail_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='recipe_id',
            new_name='cocktail_id',
        ),
    ]
